[build.environment]
  DART_SASS_VERSION = "1.70.0"
  HUGO_VERSION = "0.126.0"
  HUGO_ENV = "production"

[build]
  publish = "./public"
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    mkdir -p opt/build/repo/dart-sass && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    hugo --gc --minify
    """